sudo: required

services:
  - docker

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - ./ci-deployment/docker_ci.sh
  - ./ci-deployment/rancher_pr_deploy.sh

script:
  - docker build --build-arg NODE_ENV=development -t nhsuk/profiles .
  - docker run -e TRAVIS=true -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID -e TRAVIS_BRANCH=$TRAVIS_BRANCH -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN nhsuk/profiles sh -c "cd /code && npm run git-hook && npm run upload-coverage-coveralls"

