sudo: required

language: node_js
node_js:
  - node

services:
  - docker

env:
  global:
  - DOCKER_COMPOSE_VERSION=1.11.1
  - DOCKER_REPO=nhsuk/gp-finder
  - DOCKER_USERNAME=nhsukautomata
  - RANCHER_TEMPLATE_NAME=c2s-gp-finder
  - RANCHER_URL=https://rancher.nhschoices.net
  - RANCHER_TEMPLATE_BRANCH_NAME==feature/changes-for-ci-script

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

after_success:
  - pip install pyyaml
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - ./scripts/ci-deployment/docker_ci.sh
  - ./scripts/ci-deployment/rancher_pr_deploy.sh

script:
  - docker-compose -f docker-compose-tests.yml build travis-tests
  - docker-compose -f docker-compose-tests.yml run travis-tests

after_script:
  - docker-compose -f docker-compose-tests.yml down -v
