sudo: required

language: node_js
node_js:
  - node

services:
  - docker

install:
  - sudo sysctl -w vm.max_map_count=262144

before_install:
  - pip install docker-compose

after_success:
  - bash ./scripts/ci-deployment/deploy.sh

script:
  - ./scripts/travis-test

after_script:
  - docker-compose -f docker-compose-tests.yml down -v
