version: '2.1'

services:

  base-app:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV-development}
    command: yarn start-watch
    volumes:
      - .:/code
    environment:
      NODE_ENV: ${NODE_ENV-development}
      ES_HOST: ${ES_HOST}
      ES_PORT: ${ES_PORT}
      SPLUNK_HEC_TOKEN: ${SPLUNK_HEC_TOKEN}
      SPLUNK_HEC_ENDPOINT: ${SPLUNK_HEC_ENDPOINT-https://splunk-collector.cloudapp.net:8088}
      WEBTRENDS_ANALYTICS_TRACKING_ID: ${WEBTRENDS_ANALYTICS_TRACKING_ID-WT1}
      GOOGLE_ANALYTICS_TRACKING_ID: ${GOOGLE_ANALYTICS_TRACKING_ID-GA1}
      HOTJAR_ANALYTICS_TRACKING_ID: ${HOTJAR_ANALYTICS_TRACKING_ID-0}
      CACHE_TIMEOUT_SECONDS: 60

  gp-finder-frontend:
    extends:
      service: base-app
    links:
      - gp-finder-db:es
    ports:
      - 3000:3000
    volumes:
      - gp-finder-node_modules:/code/node_modules

  gp-finder-db:
    image: "nhsuk/profiles-db-elastic:${profiles_db_elastic_docker_image_tag-0.4.1-20170930}"

volumes:
  gp-finder-node_modules:
