version: '2.1'

services:

  base-app:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV-development}
    command: yarn run watch-dev
    volumes:
      - .:/code
    environment:
      NODE_ENV: ${NODE_ENV-development}
      SPLUNK_HEC_TOKEN: ${SPLUNK_HEC_TOKEN}
      SPLUNK_HEC_ENDPOINT: ${SPLUNK_HEC_ENDPOINT-https://splunk-collector.cloudapp.net:8088}
      WEBTRENDS_ANALYTICS_TRACKING_ID: ${WEBTRENDS_ANALYTICS_TRACKING_ID-WT1}
      GOOGLE_ANALYTICS_TRACKING_ID: ${GOOGLE_ANALYTICS_TRACKING_ID-GA1}
      HOTJAR_ANALYTICS_TRACKING_ID: ${HOTJAR_ANALYTICS_TRACKING_ID-0}

  gp-finder-frontend:
    extends:
      service: base-app
    links:
      - gp-finder-db:mongo
    ports:
      - 3000:3000
    volumes:
      - gp-finder-node_modules:/code/node_modules

  gp-finder-db:
    image: "nhsuk/profiles-db:${profiles_db_docker_image_tag-pr-44}"

volumes:
  gp-finder-node_modules:
