version: '2.1'

services:

  gp-finder-travis-test:
    build:
      context: .
      args:
        NODE_ENV: development
    command: sh -c "npm run git-hook && npm run upload-coverage-coveralls"
    volumes:
      - .:/code
      - gp-finder-travis-test-node_modules:/code/node_modules
    environment:
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      NODE_ENV: development
      TRAVIS: ${TRAVIS}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      TRAVIS_COMMIT: ${TRAVIS_COMMIT}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}

volumes:
  gp-finder-travis-test-node_modules:
